version: "3.9"

services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/code
    env_file:
      - ./.env

#  redis:
#    image: "redis:alpine"

  db:
    image: "postgres:12.1"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
    - db:/var/lib/postgresql/data
    ports:
    - "5432:5432"

volumes:
  db:
