"""empty message

Revision ID: 3e90acda5d9c
Revises: e1c83c97b5d1
Create Date: 2023-03-18 18:13:53.045436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e90acda5d9c'
down_revision = 'e1c83c97b5d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('name', sa.String(length=266), nullable=True))
    op.add_column('auth_user', sa.Column('avatar', sa.String(length=1024), nullable=True))
    op.add_column('auth_user', sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('auth_user', sa.Column('updatedAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'updatedAt')
    op.drop_column('auth_user', 'createdAt')
    op.drop_column('auth_user', 'avatar')
    op.drop_column('auth_user', 'name')
    # ### end Alembic commands ###
