"""menu_item_table

Revision ID: 4dcc1f4f47c3
Revises: 5539556b865a
Create Date: 2023-04-17 19:56:58.911151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dcc1f4f47c3'
down_revision = '5539556b865a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.Enum('alcohol_drinks', 'non_alcohol_drinks', 'snacks', 'pizza', 'sushi', name='menucategory'), nullable=True),
    sa.Column('sub_category', sa.String(length=1024), nullable=True),
    sa.Column('name', sa.String(length=1024), nullable=True),
    sa.Column('sub_name', sa.String(length=1024), nullable=True),
    sa.Column('main_unit', sa.String(length=255), nullable=True),
    sa.Column('main_price', sa.String(length=255), nullable=True),
    sa.Column('secondary_unit', sa.String(length=255), nullable=True),
    sa.Column('secondary_price', sa.String(length=255), nullable=True),
    sa.Column('special', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_item')
    # ### end Alembic commands ###
