"""add_serverd_field

Revision ID: 5539556b865a
Revises: 0ca7a47d4b6f
Create Date: 2023-04-05 19:09:05.309921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5539556b865a'
down_revision = '0ca7a47d4b6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('served', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'served')
    # ### end Alembic commands ###
