"""Add user model

Revision ID: e1c83c97b5d1
Revises: 92c1ecc289c8
Create Date: 2023-02-26 17:27:38.854732

"""
from alembic import op
import sqlalchemy as sa

from app.utils import get_hashed_password


# revision identifiers, used by Alembic.
revision = 'e1c83c97b5d1'
down_revision = '92c1ecc289c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("INSERT INTO auth_user (username, password) VALUES ('{username}', '{password_hash}')".format(
        username="admin", password_hash=get_hashed_password("admin")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
